version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: skl_nodejs
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=francesco
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    networks:
      - private

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data
    networks:
      - private

  nginx:
    container_name: nginx_app
    image: nginx
    ports:
      - "80:80"
    networks:
      - public
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  node_db_data: {}

networks:
  public:
    driver: bridge
  private:
    driver: bridge